-- 015_billing_webhook_support.sql
-- ============================================================
-- Additive-only. Ensures every column/table api/stripe-webhook.js writes to
-- actually exists. If current_period_end is missing, EVERY
-- customer.subscription.updated event 500s (Supabase PATCH rejects the unknown
-- column), Stripe keeps retrying, and after enough days of failures Stripe
-- auto-disables the whole webhook endpoint — taking checkout.session.completed
-- down with it. Safe to run even if these already exist.
-- ============================================================

-- Columns the webhook PATCHes onto product_members
ALTER TABLE product_members ADD COLUMN IF NOT EXISTS stripe_customer_id text;
ALTER TABLE product_members ADD COLUMN IF NOT EXISTS stripe_subscription_id text;
ALTER TABLE product_members ADD COLUMN IF NOT EXISTS current_period_end date;

-- Idempotency ledger for purchase confirmation emails (webhook logs here
-- after a successful Resend send; unique key prevents double-sends on retry)
CREATE TABLE IF NOT EXISTS purchase_emails_sent (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_session_id  text NOT NULL,
  product            text,
  tier               text,
  email              text,
  amount_total       integer,
  currency           text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT purchase_emails_sent_session_unique UNIQUE (stripe_session_id)
);

-- Service role bypasses RLS, but enable it so anon/authenticated can't read
-- the ledger (no policies = no access for non-service roles).
ALTER TABLE purchase_emails_sent ENABLE ROW LEVEL SECURITY;
